name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Meson Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: src/build
          #setup-options: # specify additional options to pass to Meson during setup, optional
          #options: # specify additional options to pass to Meson, optional
          meson-version: 1.3.1 # specify the version of Meson to use, default is '0.53.2'
          ninja-version: 1.11.1 # specify the version of Ninja to use, default is '1.9.0.post1'
          #gcovr-version: # specify the version of gcovr to use (if doing coverage), default is '4.2'
